service: mapper-api

custom:
  stage: ${opt:stage, self:provider.stage}

  bundle:
    linting: false
  customDomain:
    domainName: mapper.api.connorrob.com
    stage: '${self:custom.stage}'
    basePath: ''
    createRoute53Record: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager
package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  profile: me
  tracing:
    lambda: true
  environment:
    stage: ${self:custom.stage}

functions:
  getListings:
    handler: src/handlers/getListings.handler
    events:
      - http:
          path: listings
          method: GET
